[{ number: '#001', name: 'Bulbasaur', elements: %w(Grass Poison), region: 'Kanto' },
 { number: '#002', name: 'Ivysaur', elements: %w(Grass Poison), region: 'Kanto' },
 { number: '#003', name: 'Venusaur', elements: %w(Grass Poison), region: 'Kanto' },
 { number: '#004', name: 'Charmander', elements: ['Fire'], region: 'Kanto' },
 { number: '#005', name: 'Charmeleon', elements: ['Fire'], region: 'Kanto' },
 { number: '#006', name: 'Charizard', elements: %w(Fire Flying), region: 'Kanto' },
 { number: '#007', name: 'Squirtle', elements: ['Water'], region: 'Kanto' },
 { number: '#008', name: 'Wartortle', elements: ['Water'], region: 'Kanto' },
 { number: '#009', name: 'Blastoise', elements: ['Water'], region: 'Kanto' },
 { number: '#010', name: 'Caterpie', elements: ['Bug'], region: 'Kanto' },
 { number: '#011', name: 'Metapod', elements: ['Bug'], region: 'Kanto' },
 { number: '#012', name: 'Butterfree', elements: %w(Bug Flying), region: 'Kanto' },
 { number: '#013', name: 'Weedle', elements: %w(Bug Poison), region: 'Kanto' },
 { number: '#014', name: 'Kakuna', elements: %w(Bug Poison), region: 'Kanto' },
 { number: '#015', name: 'Beedrill', elements: %w(Bug Poison), region: 'Kanto' },
 { number: '#016', name: 'Pidgey', elements: %w(Normal Flying), region: 'Kanto' },
 { number: '#017', name: 'Pidgeotto', elements: %w(Normal Flying), region: 'Kanto' },
 { number: '#018', name: 'Pidgeot', elements: %w(Normal Flying), region: 'Kanto' },
 { number: '#019', name: 'Rattata', elements: ['Normal'], region: 'Kanto' },
 { number: '#020', name: 'Raticate', elements: ['Normal'], region: 'Kanto' },
 { number: '#021', name: 'Spearow', elements: %w(Normal Flying), region: 'Kanto' },
 { number: '#022', name: 'Fearow', elements: %w(Normal Flying), region: 'Kanto' },
 { number: '#023', name: 'Ekans', elements: ['Poison'], region: 'Kanto' },
 { number: '#024', name: 'Arbok', elements: ['Poison'], region: 'Kanto' },
 { number: '#025', name: 'Pikachu', elements: ['Electric'], region: 'Kanto' },
 { number: '#026', name: 'Raichu', elements: ['Electric'], region: 'Kanto' },
 { number: '#027', name: 'Sandshrew', elements: ['Ground'], region: 'Kanto' },
 { number: '#028', name: 'Sandslash', elements: ['Ground'], region: 'Kanto' },
 { number: '#029', name: 'Nidoran♀', elements: ['Poison'], region: 'Kanto' },
 { number: '#030', name: 'Nidorina', elements: ['Poison'], region: 'Kanto' },
 { number: '#031', name: 'Nidoqueen', elements: %w(Poison Ground), region: 'Kanto' },
 { number: '#032', name: 'Nidoran♂', elements: ['Poison'], region: 'Kanto' },
 { number: '#033', name: 'Nidorino', elements: ['Poison'], region: 'Kanto' },
 { number: '#034', name: 'Nidoking', elements: %w(Poison Ground), region: 'Kanto' },
 { number: '#035', name: 'Clefairy', elements: ['Normal'], region: 'Kanto' },
 { number: '#036', name: 'Clefable', elements: ['Normal'], region: 'Kanto' },
 { number: '#037', name: 'Vulpix', elements: ['Fire'], region: 'Kanto' },
 { number: '#038', name: 'Ninetales', elements: ['Fire'], region: 'Kanto' },
 { number: '#039', name: 'Jigglypuff', elements: ['Normal'], region: 'Kanto' },
 { number: '#040', name: 'Wigglytuff', elements: ['Normal'], region: 'Kanto' },
 { number: '#041', name: 'Zubat', elements: %w(Poison Flying), region: 'Kanto' },
 { number: '#042', name: 'Golbat', elements: %w(Poison Flying), region: 'Kanto' },
 { number: '#043', name: 'Oddish', elements: %w(Grass Poison), region: 'Kanto' },
 { number: '#044', name: 'Gloom', elements: %w(Grass Poison), region: 'Kanto' },
 { number: '#045', name: 'Vileplume', elements: %w(Grass Poison), region: 'Kanto' },
 { number: '#046', name: 'Paras', elements: %w(Bug Grass), region: 'Kanto' },
 { number: '#047', name: 'Parasect', elements: %w(Bug Grass), region: 'Kanto' },
 { number: '#048', name: 'Venonat', elements: %w(Bug Poison), region: 'Kanto' },
 { number: '#049', name: 'Venomoth', elements: %w(Bug Poison), region: 'Kanto' },
 { number: '#050', name: 'Diglett', elements: ['Ground'], region: 'Kanto' },
 { number: '#051', name: 'Dugtrio', elements: ['Ground'], region: 'Kanto' },
 { number: '#052', name: 'Meowth', elements: ['Normal'], region: 'Kanto' },
 { number: '#053', name: 'Persian', elements: ['Normal'], region: 'Kanto' },
 { number: '#054', name: 'Psyduck', elements: ['Water'], region: 'Kanto' },
 { number: '#055', name: 'Golduck', elements: ['Water'], region: 'Kanto' },
 { number: '#056', name: 'Mankey', elements: ['Fighting'], region: 'Kanto' },
 { number: '#057', name: 'Primeape', elements: ['Fighting'], region: 'Kanto' },
 { number: '#058', name: 'Growlithe', elements: ['Fire'], region: 'Kanto' },
 { number: '#059', name: 'Arcanine', elements: ['Fire'], region: 'Kanto' },
 { number: '#060', name: 'Poliwag', elements: ['Water'], region: 'Kanto' },
 { number: '#061', name: 'Poliwhirl', elements: ['Water'], region: 'Kanto' },
 { number: '#062', name: 'Poliwrath', elements: %w(Water Fighting), region: 'Kanto' },
 { number: '#063', name: 'Abra', elements: ['Psychic'], region: 'Kanto' },
 { number: '#064', name: 'Kadabra', elements: ['Psychic'], region: 'Kanto' },
 { number: '#065', name: 'Alakazam', elements: ['Psychic'], region: 'Kanto' },
 { number: '#066', name: 'Machop', elements: ['Fighting'], region: 'Kanto' },
 { number: '#067', name: 'Machoke', elements: ['Fighting'], region: 'Kanto' },
 { number: '#068', name: 'Machamp', elements: ['Fighting'], region: 'Kanto' },
 { number: '#069', name: 'Bellsprout', elements: ['Grass,Poison'], region: 'Kanto' },
 { number: '#070', name: 'Weepinbell', elements: ['Grass,Poison'], region: 'Kanto' },
 { number: '#071', name: 'Victreebel', elements: ['Grass,Poison'], region: 'Kanto' },
 { number: '#072', name: 'Tentacool', elements: ['Water,Poison'], region: 'Kanto' },
 { number: '#073', name: 'Tentacruel', elements: ['Water,Poison'], region: 'Kanto' },
 { number: '#074', name: 'Geodude', elements: ['Rock,Ground'], region: 'Kanto' },
 { number: '#075', name: 'Graveler', elements: ['Rock,Ground'], region: 'Kanto' },
 { number: '#076', name: 'Golem', elements: %w(Rock Ground), region: 'Kanto' },
 { number: '#077', name: 'Ponyta', elements: ['Fire'], region: 'Kanto' },
 { number: '#078', name: 'Rapidash', elements: ['Fire'], region: 'Kanto' },
 { number: '#079', name: 'Slowpoke', elements: %w(Water Psychic), region: 'Kanto' },
 { number: '#080', name: 'Slowbro', elements: %w(Water Psychic), region: 'Kanto' },
 { number: '#081', name: 'Magnemite', elements: %w(Electric Steel), region: 'Kanto' },
 { number: '#082', name: 'Magneton', elements: %w(Electric Steel), region: 'Kanto' },
 { number: '#083', name: "Farfetch'd", elements: %w(Normal Flying), region: 'Kanto' },
 { number: '#084', name: 'Doduo', elements: %w(Normal Flying), region: 'Kanto' },
 { number: '#085', name: 'Dodrio', elements: %w(Normal Flying), region: 'Kanto' },
 { number: '#086', name: 'Seel', elements: ['Water'], region: 'Kanto' },
 { number: '#087', name: 'Dewgong', elements: %w(Water Ice), region: 'Kanto' },
 { number: '#088', name: 'Grimer', elements: ['Poison'], region: 'Kanto' },
 { number: '#089', name: 'Muk', elements: ['Poison'], region: 'Kanto' },
 { number: '#090', name: 'Shellder', elements: ['Water'], region: 'Kanto' },
 { number: '#091', name: 'Cloyster', elements: %w(Water Ice), region: 'Kanto' },
 { number: '#092', name: 'Gastly', elements: %w(Ghost Poison), region: 'Kanto' },
 { number: '#093', name: 'Haunter', elements: %w(Ghost Poison), region: 'Kanto' },
 { number: '#094', name: 'Gengar', elements: %w(Ghost Poison), region: 'Kanto' },
 { number: '#095', name: 'Onix', elements: %w(Rock Ground), region: 'Kanto' },
 { number: '#096', name: 'Drowzee', elements: ['Psychic'], region: 'Kanto' },
 { number: '#097', name: 'Hypno', elements: ['Psychic'], region: 'Kanto' },
 { number: '#098', name: 'Krabby', elements: ['Water'], region: 'Kanto' },
 { number: '#099', name: 'Kingler', elements: ['Water'], region: 'Kanto' },
 { number: '#100', name: 'Voltorb', elements: ['Electric'], region: 'Kanto' },
 { number: '#101', name: 'Electrode', elements: ['Electric'], region: 'Kanto' },
 { number: '#102', name: 'Exeggcute', elements: %w(Grass Psychic), region: 'Kanto' },
 { number: '#103', name: 'Exeggutor', elements: %w(Grass Psychic), region: 'Kanto' },
 { number: '#104', name: 'Cubone', elements: ['Ground'], region: 'Kanto' },
 { number: '#105', name: 'Marowak', elements: ['Ground'], region: 'Kanto' },
 { number: '#106', name: 'Hitmonlee', elements: ['Fighting'], region: 'Kanto' },
 { number: '#107', name: 'Hitmonchan', elements: ['Fighting'], region: 'Kanto' },
 { number: '#108', name: 'Lickitung', elements: ['Normal'], region: 'Kanto' },
 { number: '#109', name: 'Koffing', elements: ['Poison'], region: 'Kanto' },
 { number: '#110', name: 'Weezing', elements: ['Poison'], region: 'Kanto' },
 { number: '#111', name: 'Rhyhorn', elements: %w(Ground Rock), region: 'Kanto' },
 { number: '#112', name: 'Rhydon', elements: %w(Ground Rock), region: 'Kanto' },
 { number: '#113', name: 'Chansey', elements: ['Normal'], region: 'Kanto' },
 { number: '#114', name: 'Tangela', elements: ['Grass'], region: 'Kanto' },
 { number: '#115', name: 'Kangaskhan', elements: ['Normal'], region: 'Kanto' },
 { number: '#116', name: 'Horsea', elements: ['Water'], region: 'Kanto' },
 { number: '#117', name: 'Seadra', elements: ['Water'], region: 'Kanto' },
 { number: '#118', name: 'Goldeen', elements: ['Water'], region: 'Kanto' },
 { number: '#119', name: 'Seaking', elements: ['Water'], region: 'Kanto' },
 { number: '#120', name: 'Staryu', elements: ['Water'], region: 'Kanto' },
 { number: '#121', name: 'Starmie', elements: %w(Water Psychic), region: 'Kanto' },
 { number: '#122', name: 'Mr. Mime', elements: ['Psychic'], region: 'Kanto' },
 { number: '#123', name: 'Scyther', elements: %w(Bug Flying), region: 'Kanto' },
 { number: '#124', name: 'Jynx', elements: %w(Ice Psychic), region: 'Kanto' },
 { number: '#125', name: 'Electabuzz', elements: ['Electric'], region: 'Kanto' },
 { number: '#126', name: 'Magmar', elements: ['Fire'], region: 'Kanto' },
 { number: '#127', name: 'Pinsir', elements: ['Bug'], region: 'Kanto' },
 { number: '#128', name: 'Tauros', elements: ['Normal'], region: 'Kanto' },
 { number: '#129', name: 'Magikarp', elements: ['Water'], region: 'Kanto' },
 { number: '#130', name: 'Gyarados', elements: %w(Water Flying), region: 'Kanto' },
 { number: '#131', name: 'Lapras', elements: %w(Water Ice), region: 'Kanto' },
 { number: '#132', name: 'Ditto', elements: ['Normal'], region: 'Kanto' },
 { number: '#133', name: 'Eevee', elements: ['Normal'], region: 'Kanto' },
 { number: '#134', name: 'Vaporeon', elements: ['Water'], region: 'Kanto' },
 { number: '#135', name: 'Jolteon', elements: ['Electric'], region: 'Kanto' },
 { number: '#136', name: 'Flareon', elements: ['Fire'], region: 'Kanto' },
 { number: '#137', name: 'Porygon', elements: ['Normal'], region: 'Kanto' },
 { number: '#138', name: 'Omanyte', elements: %w(Rock Water), region: 'Kanto' },
 { number: '#139', name: 'Omastar', elements: %w(Rock Water), region: 'Kanto' },
 { number: '#140', name: 'Kabuto', elements: %w(Rock Water), region: 'Kanto' },
 { number: '#141', name: 'Kabutops', elements: %w(Rock Water), region: 'Kanto' },
 { number: '#142', name: 'Aerodactyl', elements: %w(Rock Flying), region: 'Kanto' },
 { number: '#143', name: 'Snorlax', elements: ['Normal'], region: 'Kanto' },
 { number: '#144', name: 'Articuno', elements: %w(Ice Flying), region: 'Kanto' },
 { number: '#145', name: 'Zapdos', elements: %w(Electric Flying), region: 'Kanto' },
 { number: '#146', name: 'Moltres', elements: %w(Fire Flying), region: 'Kanto' },
 { number: '#147', name: 'Dratini', elements: ['Dragon'], region: 'Kanto' },
 { number: '#148', name: 'Dragonair', elements: ['Dragon'], region: 'Kanto' },
 { number: '#149', name: 'Dragonite', elements: %w(Dragon Flying), region: 'Kanto' },
 { number: '#150', name: 'Mewtwo', elements: ['Psychic'], region: 'Kanto' },
 { number: '#151', name: 'Mew', elements: ['Psychic'], region: 'Kanto' }]
